# Generated by Django 3.2 on 2021-05-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGyms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.TextField()),
                ('owner_first_name', models.CharField(max_length=50)),
                ('owner_last_name', models.CharField(max_length=50)),
                ('active_subscription', models.BooleanField(default=True)),
                ('last_login_ip', models.GenericIPAddressField()),
                ('country_code', models.IntegerField(max_length=7)),
                ('contact_number', models.IntegerField(max_length=15)),
                ('owner_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
