# Generated by Django 3.2 on 2021-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergyms',
            name='contact_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mastergyms',
            name='country_code',
            field=models.IntegerField(),
        ),
    ]
