# Generated by Django 3.2 on 2021-05-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0002_auto_20210515_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPassReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('token_id', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
