# Generated by Django 3.2 on 2021-05-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0003_ownerpassreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerpassreset',
            name='gym_email',
            field=models.EmailField(default=2, max_length=254),
            preserve_default=False,
        ),
    ]
