# Generated by Django 3.2 on 2021-05-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0004_ownerpassreset_gym_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergyms',
            name='contact_number',
            field=models.TextField(),
        ),
    ]
