# Generated by Django 3.2 on 2021-05-22 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0005_alter_mastergyms_contact_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gym_name', models.TextField()),
                ('gym_address', models.TextField()),
                ('gym_country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('phone_number', models.TextField()),
                ('country_code', models.IntegerField()),
                ('location', models.TextField()),
                ('is_owner', models.BooleanField(default=False)),
                ('last_login_ip', models.GenericIPAddressField()),
                ('gym_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authlogin.gymdata')),
            ],
        ),
    ]
