# Generated by Django 3.2 on 2021-05-22 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0006_gymdata_userprofiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
