# Generated by Django 3.2 on 2021-05-22 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0007_userprofiles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiles',
            name='last_login_ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
