# Generated by Django 3.2 on 2021-06-06 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0009_auto_20210530_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiles',
            name='full_name',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
