# Generated by Django 3.2 on 2021-06-06 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authlogin', '0011_alter_userprofiles_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiles',
            name='full_name',
        ),
    ]
